// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddCommand'](arg1, arg2, arg3);
}

export function AddProjectCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddProjectCommand'](arg1, arg2, arg3);
}

export function CdToPath(arg1) {
  return window['go']['app']['App']['CdToPath'](arg1);
}

export function CloseProject() {
  return window['go']['app']['App']['CloseProject']();
}

export function CloseTerminal(arg1) {
  return window['go']['app']['App']['CloseTerminal'](arg1);
}

export function CollapseAllTree() {
  return window['go']['app']['App']['CollapseAllTree']();
}

export function DeleteCommand(arg1) {
  return window['go']['app']['App']['DeleteCommand'](arg1);
}

export function DeleteProjectCommand(arg1) {
  return window['go']['app']['App']['DeleteProjectCommand'](arg1);
}

export function FSCopyPath(arg1) {
  return window['go']['app']['App']['FSCopyPath'](arg1);
}

export function FSDelete(arg1) {
  return window['go']['app']['App']['FSDelete'](arg1);
}

export function FSDeletePaths(arg1) {
  return window['go']['app']['App']['FSDeletePaths'](arg1);
}

export function FSNewFile(arg1, arg2) {
  return window['go']['app']['App']['FSNewFile'](arg1, arg2);
}

export function FSNewFolder(arg1, arg2) {
  return window['go']['app']['App']['FSNewFolder'](arg1, arg2);
}

export function FSRename(arg1, arg2) {
  return window['go']['app']['App']['FSRename'](arg1, arg2);
}

export function FSRevealInFinder(arg1) {
  return window['go']['app']['App']['FSRevealInFinder'](arg1);
}

export function GetAllFiles(arg1) {
  return window['go']['app']['App']['GetAllFiles'](arg1);
}

export function GetCWD() {
  return window['go']['app']['App']['GetCWD']();
}

export function GetCommands() {
  return window['go']['app']['App']['GetCommands']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetCurrentGalleryPath() {
  return window['go']['app']['App']['GetCurrentGalleryPath']();
}

export function GetGalleryImages(arg1) {
  return window['go']['app']['App']['GetGalleryImages'](arg1);
}

export function GetMediaBase() {
  return window['go']['app']['App']['GetMediaBase']();
}

export function GetProcessLogs(arg1) {
  return window['go']['app']['App']['GetProcessLogs'](arg1);
}

export function GetProcesses() {
  return window['go']['app']['App']['GetProcesses']();
}

export function GetProjectCommands() {
  return window['go']['app']['App']['GetProjectCommands']();
}

export function GetProjectRoot() {
  return window['go']['app']['App']['GetProjectRoot']();
}

export function GetProjectSymbols(arg1) {
  return window['go']['app']['App']['GetProjectSymbols'](arg1);
}

export function GetProjectUI() {
  return window['go']['app']['App']['GetProjectUI']();
}

export function GetRecentProjects() {
  return window['go']['app']['App']['GetRecentProjects']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetTreeNodes() {
  return window['go']['app']['App']['GetTreeNodes']();
}

export function GitBlame(arg1) {
  return window['go']['app']['App']['GitBlame'](arg1);
}

export function GitStatus() {
  return window['go']['app']['App']['GitStatus']();
}

export function IsVideo(arg1) {
  return window['go']['app']['App']['IsVideo'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['app']['App']['KillProcess'](arg1);
}

export function LSPSend(arg1, arg2) {
  return window['go']['app']['App']['LSPSend'](arg1, arg2);
}

export function LSPStart(arg1, arg2) {
  return window['go']['app']['App']['LSPStart'](arg1, arg2);
}

export function LSPStop(arg1) {
  return window['go']['app']['App']['LSPStop'](arg1);
}

export function NewTerminal() {
  return window['go']['app']['App']['NewTerminal']();
}

export function NewWindow() {
  return window['go']['app']['App']['NewWindow']();
}

export function OpenProject() {
  return window['go']['app']['App']['OpenProject']();
}

export function OpenRecentInNewWindow(arg1) {
  return window['go']['app']['App']['OpenRecentInNewWindow'](arg1);
}

export function OpenRecentProject(arg1) {
  return window['go']['app']['App']['OpenRecentProject'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['app']['App']['ReadFileBase64'](arg1);
}

export function ReadFileChunk(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadFileChunk'](arg1, arg2, arg3);
}

export function RefreshTree() {
  return window['go']['app']['App']['RefreshTree']();
}

export function RenameCommand(arg1, arg2) {
  return window['go']['app']['App']['RenameCommand'](arg1, arg2);
}

export function RenameProjectCommand(arg1, arg2) {
  return window['go']['app']['App']['RenameProjectCommand'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['ReplaceInFiles'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResizePTY(arg1, arg2) {
  return window['go']['app']['App']['ResizePTY'](arg1, arg2);
}

export function ResizePTYTab(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizePTYTab'](arg1, arg2, arg3);
}

export function RestartProcess(arg1) {
  return window['go']['app']['App']['RestartProcess'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['app']['App']['RunCommand'](arg1);
}

export function RunProjectCommand(arg1) {
  return window['go']['app']['App']['RunProjectCommand'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveNewFile(arg1, arg2) {
  return window['go']['app']['App']['SaveNewFile'](arg1, arg2);
}

export function SaveProjectUI(arg1) {
  return window['go']['app']['App']['SaveProjectUI'](arg1);
}

export function SearchInFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SearchInFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function SetQuitRequested() {
  return window['go']['app']['App']['SetQuitRequested']();
}

export function ToggleTreeNode(arg1) {
  return window['go']['app']['App']['ToggleTreeNode'](arg1);
}

export function TriggerNewFile() {
  return window['go']['app']['App']['TriggerNewFile']();
}

export function TriggerPalette() {
  return window['go']['app']['App']['TriggerPalette']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2);
}

export function WritePTY(arg1) {
  return window['go']['app']['App']['WritePTY'](arg1);
}

export function WritePTYTab(arg1, arg2) {
  return window['go']['app']['App']['WritePTYTab'](arg1, arg2);
}
