// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {commands} from '../models';
import {config} from '../models';
import {process} from '../models';
import {project} from '../models';

export function AddCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddProjectCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AssistantApprovePlan(arg1:string):Promise<void>;

export function AssistantInterrupt(arg1:string):Promise<void>;

export function AssistantPickFiles():Promise<Array<string>>;

export function AssistantSend(arg1:string,arg2:string):Promise<void>;

export function AssistantStart(arg1:string,arg2:string):Promise<string>;

export function AssistantStop(arg1:string):Promise<void>;

export function AssistantSwitchMode(arg1:string,arg2:string):Promise<void>;

export function CdToPath(arg1:string):Promise<void>;

export function CloseProject():Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CollapseAllTree():Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteProjectCommand(arg1:string):Promise<void>;

export function FSCopyPath(arg1:string):Promise<string>;

export function FSDelete(arg1:string):Promise<void>;

export function FSDeletePaths(arg1:Array<string>):Promise<void>;

export function FSDuplicate(arg1:string):Promise<void>;

export function FSMove(arg1:Array<string>,arg2:string):Promise<void>;

export function FSNewFile(arg1:string,arg2:string):Promise<void>;

export function FSNewFolder(arg1:string,arg2:string):Promise<void>;

export function FSRename(arg1:string,arg2:string):Promise<void>;

export function FSRevealInFinder(arg1:string):Promise<void>;

export function FileOutline(arg1:string):Promise<Array<app.OutlineSym>>;

export function GetAllFiles(arg1:string):Promise<Array<string>>;

export function GetCWD():Promise<string>;

export function GetCommands():Promise<Array<commands.SavedCommand>>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentGalleryPath():Promise<string>;

export function GetGalleryImages(arg1:string):Promise<Array<string>>;

export function GetMediaBase():Promise<string>;

export function GetProcessLogs(arg1:string):Promise<Array<string>>;

export function GetProcesses():Promise<Array<process.Process>>;

export function GetProjectCommands():Promise<Array<project.Cmd>>;

export function GetProjectRoot():Promise<string>;

export function GetProjectSymbols(arg1:string):Promise<Array<app.Symbol>>;

export function GetProjectUI():Promise<project.UIState>;

export function GetRecentProjects():Promise<Array<project.RecentEntry>>;

export function GetTheme():Promise<app.ThemeDTO>;

export function GetTreeNodes():Promise<Array<app.TreeNodeDTO>>;

export function GitBlame(arg1:string):Promise<Array<app.BlameLine>>;

export function GitBranches():Promise<Array<string>>;

export function GitCheckout(arg1:string):Promise<void>;

export function GitCommit(arg1:string):Promise<void>;

export function GitDiff(arg1:string):Promise<Array<app.DiffLine>>;

export function GitDiffText(arg1:string):Promise<string>;

export function GitStage(arg1:string):Promise<void>;

export function GitStatus():Promise<app.GitStatusDTO>;

export function GitUnstage(arg1:string):Promise<void>;

export function IsVideo(arg1:string):Promise<boolean>;

export function KillProcess(arg1:string):Promise<void>;

export function LSPSend(arg1:string,arg2:string):Promise<void>;

export function LSPStart(arg1:string,arg2:string):Promise<boolean>;

export function LSPStop(arg1:string):Promise<void>;

export function NewTerminal():Promise<string>;

export function NewWindow():Promise<void>;

export function OpenProject():Promise<string>;

export function OpenRecentInNewWindow(arg1:string):Promise<void>;

export function OpenRecentProject(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadFileChunk(arg1:string,arg2:number,arg3:number):Promise<app.FileChunk>;

export function RefreshTree():Promise<void>;

export function RenameCommand(arg1:string,arg2:string):Promise<void>;

export function RenameProjectCommand(arg1:string,arg2:string):Promise<void>;

export function ReplaceInFiles(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:boolean):Promise<number>;

export function ResizePTY(arg1:number,arg2:number):Promise<void>;

export function ResizePTYTab(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartProcess(arg1:string):Promise<void>;

export function RunCommand(arg1:string):Promise<void>;

export function RunProjectCommand(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveNewFile(arg1:string,arg2:string):Promise<string>;

export function SaveProjectUI(arg1:project.UIState):Promise<void>;

export function SearchInFiles(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<Array<app.SearchResultDTO>>;

export function SetQuitRequested():Promise<void>;

export function StashDropped(arg1:Array<string>):Promise<Array<string>>;

export function StopProcess(arg1:string):Promise<void>;

export function ToggleTreeNode(arg1:string):Promise<void>;

export function TriggerNewFile():Promise<void>;

export function TriggerPalette():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WritePTY(arg1:string):Promise<void>;

export function WritePTYTab(arg1:string,arg2:string):Promise<void>;
