// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddCommand'](arg1, arg2, arg3);
}

export function AddProjectCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddProjectCommand'](arg1, arg2, arg3);
}

export function AddWorkspaceRoot() {
  return window['go']['app']['App']['AddWorkspaceRoot']();
}

export function AssistantInterrupt(arg1) {
  return window['go']['app']['App']['AssistantInterrupt'](arg1);
}

export function AssistantPickFiles() {
  return window['go']['app']['App']['AssistantPickFiles']();
}

export function AssistantRespondPermission(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AssistantRespondPermission'](arg1, arg2, arg3, arg4);
}

export function AssistantSend(arg1, arg2) {
  return window['go']['app']['App']['AssistantSend'](arg1, arg2);
}

export function AssistantStart(arg1, arg2) {
  return window['go']['app']['App']['AssistantStart'](arg1, arg2);
}

export function AssistantStop(arg1) {
  return window['go']['app']['App']['AssistantStop'](arg1);
}

export function AssistantSwitchMode(arg1, arg2) {
  return window['go']['app']['App']['AssistantSwitchMode'](arg1, arg2);
}

export function CdToPath(arg1) {
  return window['go']['app']['App']['CdToPath'](arg1);
}

export function CloseProject() {
  return window['go']['app']['App']['CloseProject']();
}

export function CloseTerminal(arg1) {
  return window['go']['app']['App']['CloseTerminal'](arg1);
}

export function CollapseAllTree() {
  return window['go']['app']['App']['CollapseAllTree']();
}

export function CompletionSuggest(arg1, arg2) {
  return window['go']['app']['App']['CompletionSuggest'](arg1, arg2);
}

export function DebugContinue() {
  return window['go']['app']['App']['DebugContinue']();
}

export function DebugSetBreakpoints(arg1, arg2) {
  return window['go']['app']['App']['DebugSetBreakpoints'](arg1, arg2);
}

export function DebugStart(arg1, arg2) {
  return window['go']['app']['App']['DebugStart'](arg1, arg2);
}

export function DebugStepIn() {
  return window['go']['app']['App']['DebugStepIn']();
}

export function DebugStepOut() {
  return window['go']['app']['App']['DebugStepOut']();
}

export function DebugStepOver() {
  return window['go']['app']['App']['DebugStepOver']();
}

export function DebugStop() {
  return window['go']['app']['App']['DebugStop']();
}

export function DeleteCommand(arg1) {
  return window['go']['app']['App']['DeleteCommand'](arg1);
}

export function DeleteProjectCommand(arg1) {
  return window['go']['app']['App']['DeleteProjectCommand'](arg1);
}

export function EditShareBroadcast(arg1, arg2) {
  return window['go']['app']['App']['EditShareBroadcast'](arg1, arg2);
}

export function ExportSettingsFile(arg1) {
  return window['go']['app']['App']['ExportSettingsFile'](arg1);
}

export function FSCopyPath(arg1) {
  return window['go']['app']['App']['FSCopyPath'](arg1);
}

export function FSDelete(arg1) {
  return window['go']['app']['App']['FSDelete'](arg1);
}

export function FSDeletePaths(arg1) {
  return window['go']['app']['App']['FSDeletePaths'](arg1);
}

export function FSDuplicate(arg1) {
  return window['go']['app']['App']['FSDuplicate'](arg1);
}

export function FSMove(arg1, arg2) {
  return window['go']['app']['App']['FSMove'](arg1, arg2);
}

export function FSNewFile(arg1, arg2) {
  return window['go']['app']['App']['FSNewFile'](arg1, arg2);
}

export function FSNewFolder(arg1, arg2) {
  return window['go']['app']['App']['FSNewFolder'](arg1, arg2);
}

export function FSRename(arg1, arg2) {
  return window['go']['app']['App']['FSRename'](arg1, arg2);
}

export function FSRevealInFinder(arg1) {
  return window['go']['app']['App']['FSRevealInFinder'](arg1);
}

export function FileOutline(arg1) {
  return window['go']['app']['App']['FileOutline'](arg1);
}

export function FileTests(arg1) {
  return window['go']['app']['App']['FileTests'](arg1);
}

export function GetAllFiles(arg1) {
  return window['go']['app']['App']['GetAllFiles'](arg1);
}

export function GetCWD() {
  return window['go']['app']['App']['GetCWD']();
}

export function GetCommands() {
  return window['go']['app']['App']['GetCommands']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetCurrentGalleryPath() {
  return window['go']['app']['App']['GetCurrentGalleryPath']();
}

export function GetEditShareGuests(arg1) {
  return window['go']['app']['App']['GetEditShareGuests'](arg1);
}

export function GetExtensions() {
  return window['go']['app']['App']['GetExtensions']();
}

export function GetGalleryImages(arg1) {
  return window['go']['app']['App']['GetGalleryImages'](arg1);
}

export function GetGoTests(arg1) {
  return window['go']['app']['App']['GetGoTests'](arg1);
}

export function GetLiveShareGuests(arg1) {
  return window['go']['app']['App']['GetLiveShareGuests'](arg1);
}

export function GetMediaBase() {
  return window['go']['app']['App']['GetMediaBase']();
}

export function GetProcessLogs(arg1) {
  return window['go']['app']['App']['GetProcessLogs'](arg1);
}

export function GetProcesses() {
  return window['go']['app']['App']['GetProcesses']();
}

export function GetProjectCommands() {
  return window['go']['app']['App']['GetProjectCommands']();
}

export function GetProjectRoot() {
  return window['go']['app']['App']['GetProjectRoot']();
}

export function GetProjectSymbols(arg1) {
  return window['go']['app']['App']['GetProjectSymbols'](arg1);
}

export function GetProjectUI() {
  return window['go']['app']['App']['GetProjectUI']();
}

export function GetRecentFiles() {
  return window['go']['app']['App']['GetRecentFiles']();
}

export function GetRecentProjects() {
  return window['go']['app']['App']['GetRecentProjects']();
}

export function GetStartupFile() {
  return window['go']['app']['App']['GetStartupFile']();
}

export function GetTasks() {
  return window['go']['app']['App']['GetTasks']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetTreeNodes() {
  return window['go']['app']['App']['GetTreeNodes']();
}

export function GetWorkspaceRoots() {
  return window['go']['app']['App']['GetWorkspaceRoots']();
}

export function GitBlame(arg1) {
  return window['go']['app']['App']['GitBlame'](arg1);
}

export function GitBranches() {
  return window['go']['app']['App']['GitBranches']();
}

export function GitBranchesForRoot(arg1) {
  return window['go']['app']['App']['GitBranchesForRoot'](arg1);
}

export function GitCheckout(arg1) {
  return window['go']['app']['App']['GitCheckout'](arg1);
}

export function GitCheckoutForRoot(arg1, arg2) {
  return window['go']['app']['App']['GitCheckoutForRoot'](arg1, arg2);
}

export function GitCommit(arg1) {
  return window['go']['app']['App']['GitCommit'](arg1);
}

export function GitCommitForRoot(arg1, arg2) {
  return window['go']['app']['App']['GitCommitForRoot'](arg1, arg2);
}

export function GitDiff(arg1) {
  return window['go']['app']['App']['GitDiff'](arg1);
}

export function GitDiffText(arg1) {
  return window['go']['app']['App']['GitDiffText'](arg1);
}

export function GitStage(arg1) {
  return window['go']['app']['App']['GitStage'](arg1);
}

export function GitStatus() {
  return window['go']['app']['App']['GitStatus']();
}

export function GitStatusForRoots(arg1) {
  return window['go']['app']['App']['GitStatusForRoots'](arg1);
}

export function GitUnstage(arg1) {
  return window['go']['app']['App']['GitUnstage'](arg1);
}

export function ImportSettingsFile() {
  return window['go']['app']['App']['ImportSettingsFile']();
}

export function IsEditSharing(arg1) {
  return window['go']['app']['App']['IsEditSharing'](arg1);
}

export function IsLiveSharing(arg1) {
  return window['go']['app']['App']['IsLiveSharing'](arg1);
}

export function IsRemoteProject() {
  return window['go']['app']['App']['IsRemoteProject']();
}

export function IsVideo(arg1) {
  return window['go']['app']['App']['IsVideo'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['app']['App']['KillProcess'](arg1);
}

export function LSPSend(arg1, arg2) {
  return window['go']['app']['App']['LSPSend'](arg1, arg2);
}

export function LSPStart(arg1, arg2) {
  return window['go']['app']['App']['LSPStart'](arg1, arg2);
}

export function LSPStop(arg1) {
  return window['go']['app']['App']['LSPStop'](arg1);
}

export function NewTerminal() {
  return window['go']['app']['App']['NewTerminal']();
}

export function NewWindow() {
  return window['go']['app']['App']['NewWindow']();
}

export function OllamaListModels(arg1) {
  return window['go']['app']['App']['OllamaListModels'](arg1);
}

export function OpenProject() {
  return window['go']['app']['App']['OpenProject']();
}

export function OpenRecentFileInNewWindow(arg1) {
  return window['go']['app']['App']['OpenRecentFileInNewWindow'](arg1);
}

export function OpenRecentInNewWindow(arg1) {
  return window['go']['app']['App']['OpenRecentInNewWindow'](arg1);
}

export function OpenRecentProject(arg1) {
  return window['go']['app']['App']['OpenRecentProject'](arg1);
}

export function OpenRemoteProject(arg1, arg2) {
  return window['go']['app']['App']['OpenRemoteProject'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['app']['App']['ReadFileBase64'](arg1);
}

export function ReadFileChunk(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadFileChunk'](arg1, arg2, arg3);
}

export function RefreshTree() {
  return window['go']['app']['App']['RefreshTree']();
}

export function RemoveWorkspaceRoot(arg1) {
  return window['go']['app']['App']['RemoveWorkspaceRoot'](arg1);
}

export function RenameCommand(arg1, arg2) {
  return window['go']['app']['App']['RenameCommand'](arg1, arg2);
}

export function RenameProjectCommand(arg1, arg2) {
  return window['go']['app']['App']['RenameProjectCommand'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['ReplaceInFiles'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ResizePTY(arg1, arg2) {
  return window['go']['app']['App']['ResizePTY'](arg1, arg2);
}

export function ResizePTYTab(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizePTYTab'](arg1, arg2, arg3);
}

export function RestartProcess(arg1) {
  return window['go']['app']['App']['RestartProcess'](arg1);
}

export function RevealInTree(arg1) {
  return window['go']['app']['App']['RevealInTree'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['app']['App']['RunCommand'](arg1);
}

export function RunGoTest(arg1, arg2) {
  return window['go']['app']['App']['RunGoTest'](arg1, arg2);
}

export function RunProjectCommand(arg1) {
  return window['go']['app']['App']['RunProjectCommand'](arg1);
}

export function RunTask(arg1) {
  return window['go']['app']['App']['RunTask'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveNewFile(arg1, arg2) {
  return window['go']['app']['App']['SaveNewFile'](arg1, arg2);
}

export function SaveProjectUI(arg1) {
  return window['go']['app']['App']['SaveProjectUI'](arg1);
}

export function SearchInFiles(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['SearchInFiles'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetEditShareGuestPermission(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetEditShareGuestPermission'](arg1, arg2, arg3);
}

export function SetExtensionEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetExtensionEnabled'](arg1, arg2);
}

export function SetLiveShareGuestPermission(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetLiveShareGuestPermission'](arg1, arg2, arg3);
}

export function SetQuitRequested() {
  return window['go']['app']['App']['SetQuitRequested']();
}

export function StartEditShare(arg1) {
  return window['go']['app']['App']['StartEditShare'](arg1);
}

export function StartLiveShare(arg1) {
  return window['go']['app']['App']['StartLiveShare'](arg1);
}

export function StashDropped(arg1) {
  return window['go']['app']['App']['StashDropped'](arg1);
}

export function StopEditShare(arg1) {
  return window['go']['app']['App']['StopEditShare'](arg1);
}

export function StopLiveShare(arg1) {
  return window['go']['app']['App']['StopLiveShare'](arg1);
}

export function StopProcess(arg1) {
  return window['go']['app']['App']['StopProcess'](arg1);
}

export function ToggleTreeNode(arg1) {
  return window['go']['app']['App']['ToggleTreeNode'](arg1);
}

export function TriggerNewFile() {
  return window['go']['app']['App']['TriggerNewFile']();
}

export function TriggerPalette() {
  return window['go']['app']['App']['TriggerPalette']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2);
}

export function WritePTY(arg1) {
  return window['go']['app']['App']['WritePTY'](arg1);
}

export function WritePTYTab(arg1, arg2) {
  return window['go']['app']['App']['WritePTYTab'](arg1, arg2);
}
