// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {config} from '../models';
import {process} from '../models';
import {project} from '../models';
import {app} from '../models';

export function CdToPath(arg1:string):Promise<void>;

export function CloseProject():Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CollapseAllTree():Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteProjectCommand(arg1:string):Promise<void>;

export function FSCopyPath(arg1:string):Promise<string>;

export function FSDelete(arg1:string):Promise<void>;

export function FSNewFile(arg1:string,arg2:string):Promise<void>;

export function FSNewFolder(arg1:string,arg2:string):Promise<void>;

export function FSRename(arg1:string,arg2:string):Promise<void>;

export function FSRevealInFinder(arg1:string):Promise<void>;

export function GetAllFiles(arg1:string):Promise<Array<string>>;

export function GetCWD():Promise<string>;

export function GetCommands():Promise<Array<commands.SavedCommand>>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentGalleryPath():Promise<string>;

export function GetGalleryImages(arg1:string):Promise<Array<string>>;

export function GetProcessLogs(arg1:string):Promise<Array<string>>;

export function GetProcesses():Promise<Array<process.Process>>;

export function GetProjectCommands():Promise<Array<project.Cmd>>;

export function GetProjectRoot():Promise<string>;

export function GetRecentProjects():Promise<Array<project.RecentEntry>>;

export function GetTheme():Promise<app.ThemeDTO>;

export function GetTreeNodes():Promise<Array<app.TreeNodeDTO>>;

export function IsVideo(arg1:string):Promise<boolean>;

export function KillProcess(arg1:string):Promise<void>;

export function NewTerminal():Promise<string>;

export function NewWindow():Promise<void>;

export function OpenProject():Promise<string>;

export function OpenRecentProject(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function RefreshTree():Promise<void>;

export function RenameCommand(arg1:string,arg2:string):Promise<void>;

export function ReplaceInFiles(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:boolean):Promise<number>;

export function ResizePTY(arg1:number,arg2:number):Promise<void>;

export function ResizePTYTab(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartProcess(arg1:string):Promise<void>;

export function RunCommand(arg1:string):Promise<void>;

export function RunProjectCommand(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveNewFile(arg1:string,arg2:string):Promise<string>;

export function SearchInFiles(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<Array<app.SearchResultDTO>>;

export function ToggleTreeNode(arg1:string):Promise<void>;

export function TriggerNewFile():Promise<void>;

export function TriggerPalette():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WritePTY(arg1:string):Promise<void>;

export function WritePTYTab(arg1:string,arg2:string):Promise<void>;
